### ISSUE TITLE
Better integration of community forum

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds-bs4-pybossa-theme#17]
For example, show latest topics on the homepage

**Comment by mialondon** [comment]
Also, link to discussion forum from task pages to encourage people to discuss specific items. Can we provide a generally accessible link for each item (from the IIIF manifest) so it's easy for them to let people know what they're referring to?

**Comment by alexandermendes** [comment]
Good idea, there is now some functionality to add 'Favourite Tasks', which can then be viewed/shared etc. from a gallery in your profile page. I've also added the manifest metadata to a modal in the viewer (see below), and I'll add an image link there too.

![untitled](https://cloud.githubusercontent.com/assets/5636273/25665801/8fcc3c7e-3016-11e7-8155-e29808abb1f7.png)

Still need to figure out how to organise the forum pages but I suppose generating one topic for each volume sounds reasonable (Playbills: Margate etc.).
