### ISSUE TITLE
Change 'Add comment' to 'Leave a note'

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-bs4-pybossa-theme#38]
And change the textarea text to 'Leave a note about the image or issues with this task, including dates or theatres not mentioned in the volume title'

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/project-playbills-mark#21

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/project-playbills-mark#22
