### ISSUE TITLE
Investigate what would be required to add meta-categories to Pybossa architecture

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-bs4-pybossa-theme#44]
We want to be able to group together local theatres with a landing page for e.g. Margate or Plymouth. Each meta-category would have a description (e.g. x theatres in Margate, something history something) and a list of projects (e.g. volumes of playbills from the area). 

So: Playbills / Meta-Category (Margate) / Category (volume of playbills Theatre name + date range).

**Comment by alexandermendes** [comment]
So I think what we're really talking about here is creating separate instances of PyBossa for each meta-category (Playbills, Card Catalogues etc.). If we look at the playbills, we not only want to be able to group the current categories but want to create a playbills homepage, an about page and probably statistics and other pages specifically related to the playbills. If we start to think about what that looks like it's basically the model we already have but with the whole site tailored to one meta-category.

I reckon we basically want a root LibCrowds (Flask) application with a homepage and overall statistics and so on, then beneath that we can dispatch a PyBossa application for each meta-category. This shouldn't be too difficult to implement and I think makes more sense than making what would be some big changes to the core PyBossa code.

I'll set up an example of how this might look for the Playbills on our test server.

**Comment by alexandermendes** [comment]
The only bit that might be tricky with the above approach is how to handle user statistics. Things like do we want to record all contributions to the Playbills/Card Catalogues separately, or do we want to record overall contributions for all project types. The first would be easier and possibly makes more sense?

**Comment by alexandermendes** [comment]
This will now be dealt with under #52
