### ISSUE TITLE
Decide when and how to link people to forum pages

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-bs4-pybossa-theme#45]

**Comment by alexandermendes** [comment]
Will drop the "latest topic" section from the homepage and possibly embed comments at the bottom of some project intro pages, rather than in a sidebar.

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/vue-pybossa-frontend#11

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/vue-pybossa-frontend#12
